# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param synth.incrementalSynthesisCache C:/Users/zhangtao/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-8676-DESKTOP-6DUCG5H/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.cache/wt [current_project]
set_property parent.project_path C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/zhangtao/Desktop/PQM/FPGA/data/font16x32_row.coe
add_files C:/Users/zhangtao/Desktop/PQM/FPGA/data/font10x20_row.coe
add_files C:/Users/zhangtao/Desktop/PQM/FPGA/data/cos_qw_0p2deg_x10000.coe
add_files -quiet C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/AD7606_Parallel_DRIVER_synth_1/AD7606_Parallel_DRIVER.dcp
set_property used_in_implementation false [get_files C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/AD7606_Parallel_DRIVER_synth_1/AD7606_Parallel_DRIVER.dcp]
add_files -quiet C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/uart_synth_1/uart.dcp
set_property used_in_implementation false [get_files C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/uart_synth_1/uart.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/SignalProcessing/adc_frame_capture_runtime.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/binary2bcd.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/clk_div.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/BasicMath/cos_lookup_x10000.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/BasicMath/divider_unsigned.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/SignalProcessing/frequency_measure.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/touch/i2c_dri.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/lcd_display.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/lcd_display_bg.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/lcd_display_text.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/lcd_driver.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/lcd_rgb_char.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/SignalProcessing/mean_filter_decim8_runtime.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/BasicMath/multiplier_signed.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/SignalProcessing/p2p_measure.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/SignalProcessing/phase_diff_calc.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/SignalProcessing/power_metrics_calc.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/rd_id.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/BasicMath/rms_signed_runtime.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/BasicMath/signed_code_to_digits_x100.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/BasicMath/sqrt_unsigned.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/GraphicsLoad/text_display_preprocess.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/text_packet_double_buffer.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/touch/touch_dri.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/touch/touch_state.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/touch/touch_top.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/SignalProcessing/ui_rms_filtered_runtime.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/SignalProcessing/ui_rms_measure.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/BasicMath/value_x100_to_digits.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/GraphicsLoad/wave_display_capture.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/GraphicsLoad/wave_display_resampler.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/GraphicsLoad/wave_frame_writer.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/GraphicsLoad/wave_history_buffer.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/wave_pixel_detector.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/GraphicsLoad/wave_trigger_core.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/SignalProcessing/zero_code_tracker.v
  C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/main.v
}
read_ip -quiet C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_font_16x32/blk_mem_gen_font_16x32.xci
set_property used_in_implementation false [get_files -all c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_font_16x32/blk_mem_gen_font_16x32_ooc.xdc]

read_ip -quiet C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_font_10x20/blk_mem_gen_font_10x20.xci
set_property used_in_implementation false [get_files -all c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_font_10x20/blk_mem_gen_font_10x20_ooc.xdc]

read_ip -quiet C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_ram0/blk_mem_gen_ram0.xci
set_property used_in_implementation false [get_files -all c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_ram0/blk_mem_gen_ram0_ooc.xdc]

read_ip -quiet C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/ROM_COS_0p2deg/ROM_COS_0p2deg.xci
set_property used_in_implementation false [get_files -all c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/ROM_COS_0p2deg/ROM_COS_0p2deg_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.xdc
set_property used_in_implementation false [get_files C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
