# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/ILA_ADC_DRIVER/ILA_ADC_DRIVER.xci
# IP: The module: 'ILA_ADC_DRIVER' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/ILA_ADC_DRIVER/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ADC_DRIVER'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/ILA_ADC_DRIVER/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ADC_DRIVER'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/ILA_ADC_DRIVER/ILA_ADC_DRIVER_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ADC_DRIVER'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/ILA_ADC_DRIVER/ILA_ADC_DRIVER.xci
# IP: The module: 'ILA_ADC_DRIVER' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/ILA_ADC_DRIVER/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ADC_DRIVER'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/ILA_ADC_DRIVER/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ADC_DRIVER'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/ILA_ADC_DRIVER/ILA_ADC_DRIVER_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ADC_DRIVER'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
