set_property SRC_FILE_INFO {cfile:c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:../../../../../PQM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:1 order:EARLY scoped_inst:u_clk_wiz_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_font_16x32/blk_mem_gen_font_16x32/blk_mem_gen_font_16x32_in_context.xdc rfile:../../../../../PQM.srcs/sources_1/ip/blk_mem_gen_font_16x32/blk_mem_gen_font_16x32/blk_mem_gen_font_16x32_in_context.xdc id:2 order:EARLY scoped_inst:u_lcd_rgb_char/u_lcd_display/u_font_16x32} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_font_10x20/blk_mem_gen_font_10x20/blk_mem_gen_font_10x20_in_context.xdc rfile:../../../../../PQM.srcs/sources_1/ip/blk_mem_gen_font_10x20/blk_mem_gen_font_10x20/blk_mem_gen_font_10x20_in_context.xdc id:3 order:EARLY scoped_inst:u_lcd_rgb_char/u_lcd_display/u_font_10x20} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_ram0/blk_mem_gen_ram0/blk_mem_gen_ram0_in_context.xdc rfile:../../../../../PQM.srcs/sources_1/ip/blk_mem_gen_ram0/blk_mem_gen_ram0/blk_mem_gen_ram0_in_context.xdc id:4 order:EARLY scoped_inst:u_lcd_rgb_char/u_lcd_display/u_wave_frame_ram} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.xdc rfile:../../../../../PQM.xdc id:5} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name u_clk_wiz_0/clk_out1 -source [get_ports sys_clk] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins u_clk_wiz_0/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name u_clk_wiz_0/clk_out2 -source [get_ports sys_clk] -edges {1 2 3} -edge_shift {0.000 10.000 20.000} [get_pins u_clk_wiz_0/clk_out2]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name u_clk_wiz_0/clk_out3 -source [get_ports sys_clk] -edges {1 2 3} -edge_shift {13.333 23.333 33.333} [get_pins u_clk_wiz_0/clk_out3]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports sys_clk]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports sys_clk]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_clk_wiz_0]
current_instance u_lcd_rgb_char/u_lcd_display/u_font_16x32
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_lcd_rgb_char/u_lcd_display/u_font_16x32]
current_instance u_lcd_rgb_char/u_lcd_display/u_font_10x20
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_lcd_rgb_char/u_lcd_display/u_font_10x20]
current_instance u_lcd_rgb_char/u_lcd_display/u_wave_frame_ram
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_lcd_rgb_char/u_lcd_display/u_wave_frame_ram]
set_property src_info {type:XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
set_property src_info {type:XDC file:5 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports sys_rst_n]
set_property src_info {type:XDC file:5 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[7]}]
set_property src_info {type:XDC file:5 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[6]}]
set_property src_info {type:XDC file:5 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[5]}]
set_property src_info {type:XDC file:5 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[4]}]
set_property src_info {type:XDC file:5 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[3]}]
set_property src_info {type:XDC file:5 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[2]}]
set_property src_info {type:XDC file:5 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[1]}]
set_property src_info {type:XDC file:5 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[0]}]
set_property src_info {type:XDC file:5 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk]
set_property src_info {type:XDC file:5 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ad_otr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_clk_wiz_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_lcd_rgb_char/u_lcd_display/u_font_16x32]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_lcd_rgb_char/u_lcd_display/u_font_10x20]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_lcd_rgb_char/u_lcd_display/u_wave_frame_ram]
