# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/synth_1/.Xil/Vivado-10156-DESKTOP-6DUCG5H/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/clk_wiz_0
    c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_font_16x32
    c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_font_10x20
  } {
      D:/zt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/zt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/clk_wiz_0
    c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_font_16x32
    c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_font_10x20
  } {
      C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/synth_1/.Xil/Vivado-10156-DESKTOP-6DUCG5H/realtime/clk_wiz_0_stub.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/synth_1/.Xil/Vivado-10156-DESKTOP-6DUCG5H/realtime/blk_mem_gen_font_16x32_stub.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/synth_1/.Xil/Vivado-10156-DESKTOP-6DUCG5H/realtime/blk_mem_gen_font_10x20_stub.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/synth_1/.Xil/Vivado-10156-DESKTOP-6DUCG5H/realtime/blk_mem_gen_ram0_stub.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/ADC_TEMP/adc_abs_voltage_calc.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/ADC_TEMP/adc_abs_voltage_top.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/ADC_TEMP/adc_sample_average.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/ADC_TEMP/adc_voltage_digits.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/ADC_TEMP/adc_zero_calibrator.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/binary2bcd.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/clk_div.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/divider_unsigned.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/touch/i2c_dri.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/lcd_display.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/lcd_display_bg.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/lcd_display_text.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/lcd_driver.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/lcd_rgb_char.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/display/rd_id.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/signal_rms_calc.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/touch/touch_dri.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/touch/touch_state.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/lcd/touch/touch_top.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/uart/uart.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/uart/uart_rx.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/uart/uart_tx.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/DataProcessor/wave_frame_capture.v
      C:/Users/zhangtao/Desktop/PQM/FPGA/rtl/main.v
    }
      rt::read_vhdl -lib xpm D:/zt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/synth_1/.Xil/Vivado-10156-DESKTOP-6DUCG5H/realtime/main_synth.xdc
    rt::sdcChecksum
    set rt::top main
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.cache/wt}
    rt::set_parameter enableSplitFlowPath "C:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.runs/synth_1/.Xil/Vivado-10156-DESKTOP-6DUCG5H/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
