# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_ram0/blk_mem_gen_ram0.xci
# IP: The module: 'blk_mem_gen_ram0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_ram0/blk_mem_gen_ram0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_ram0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_ram0/blk_mem_gen_ram0.xci
# IP: The module: 'blk_mem_gen_ram0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhangtao/Desktop/PQM/FPGA/prj/PQM.srcs/sources_1/ip/blk_mem_gen_ram0/blk_mem_gen_ram0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_ram0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
