######################################################################
#
# File name : tb_top_dvm_compile.do
# Created on: Mon Sep 08 15:59:43 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
F:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

F:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modeltech64_2020.4\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../../rtl/clk_div.v" \
"../../../../../rtl/lcd_disp_char.v" \
"../../../../../rtl/lcd_display.v" \
"../../../../../rtl/lcd_driver.v" \
"../../../../../rtl/rd_id.v" \
"../../../../../rtl/test_voltage.v" \
"../../../../../rtl/top_dvm.v" \
"../../../../../rtl/voltage_calibrator.v" \
"../../../../../rtl/voltage_data.v" \
"../../../../../sim/tb_top_dvm.v" \


# compile glbl module
F:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

