######################################################################
#
# File name : tb_top_dvm_simulate.do
# Created on: Mon Sep 08 15:59:48 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_top_dvm xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_top_dvm_wave.do}

view wave
view structure
view signals

do {tb_top_dvm.udo}

run 1000ns
