######################################################################
#
# File name : tb_top_dvm_wave.do
# Created on: Wed Jul 30 11:08:08 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
